### ISSUE TITLE
Worker fails to register after upgrade to GPUStack v2.2.0 ('NoneType' object has no attribute 'create_async')

### ISSUE THREAD

**Issue by tingtingj73-ux** [gpustack/gpustack#5714]
### GPUStack version

2.2.0

### ▶️ Steps to reproduce

After upgrading GPUStack from v2.1.2 to v2.2.0, the worker fails to register with the server.
The worker starts normally, but repeatedly fails during registration with the following error:
Failed to register worker: 'NoneType' object has no attribute 'create_async'
Retrying to get worker ID (attempt 4) due to: 'NoneType' object has no attribute 'create_async'
Eventually, the worker shuts down after multiple retries.

### ✅ Expected result

Worker should successfully register to server and start normal scheduling.

### ❌ Actual result

Worker fails to register with repeated error:
'NoneType' object has no attribute 'create_async'
Worker eventually exits.

**Comment by gitlawr** [comment]
The error implies that WorkerRegistrationClient is not initialized in https://github.com/gpustack/gpustack/blob/c45250568b6de183a615bea6e0693e517cecdb40/gpustack/config/registration.py#L52

It may happen if both the registration token or the registration token file is not available.

Can you provide the exact worker start command? Is it possible that it used `--token/GPUSTACK_TOKEN` before but it's missing during the upgrade?

To recover, you should be able to get the registration token from `Add Worker` UI, then pass it to the worker via `--token/GPUSTACK_TOKEN`.

**Comment by tingtingj73-ux** [comment]
Thank you, the problem has been found. The token was not sent to the worker.
