### ISSUE TITLE
Database migration failed when upgrading to v0.7.0

### ISSUE THREAD

**Issue by gitlawr** [gpustack/gpustack#2635]
**Describe the bug**

```
2025-07-28 07:09:37.301006+00:00 - gpustack.cmd.start - INFO - GPUStack version: v0.7.0 (13f96d7)
2025-07-28 07:09:37.305404+00:00 - gpustack.server.server - INFO - Starting GPUStack server.
2025-07-28 07:09:37.305810+00:00 - gpustack.server.server - INFO - Running database migration.
2025-07-28 07:09:37.384257+00:00 - gpustack.cmd.start - ERROR - Error running server: Database migration failed: 'NoneType' object has no attribute 'get'
2025-07-28 07:09:37.384344+00:00 - gpustack.cmd.start - INFO - Server has shut down.

```

Multiple users encounter the above errors.

**Case 1**

Upgrade from `gpustack/gpustack:main-cu11.8` to `gpustack/gpustack:v0.7.0-cpu`

Version before the upgrade:
```
# gpustack version
v0.0.0 (4755365)
```

**Case 2**

Upgrade from v0.6.1 to v0.7.0

**Comment by gitlawr** [comment]
Script for diagnose(change `/var/lib/gpustack/database.db` to your path according to your setup):
```
import sqlite3

conn = sqlite3.connect('/var/lib/gpustack/database.db')
cursor = conn.cursor()

query = """
SELECT id, distributed_servers
FROM model_instances
WHERE distributed_servers IS NOT NULL;
"""
cursor.execute(query)

rows = cursor.fetchall()

for row in rows:
    print("ID:", row[0], "| distributed_servers:", row[1])

cursor.close()
conn.close()
```

**Comment by gitlawr** [comment]
Feedback from users executing the diagnose script:

```
ID: 169 | distributed_servers: {"rpc_servers": null, "ray_actors": null}
ID: 170 | distributed_servers: {"rpc_servers": null, "ray_actors": null}
ID: 171 | distributed_servers: null
ID: 172 | distributed_servers: null
```

**Comment by gitlawr** [comment]
Possible fix: Run the following script to update 'null' distributed_servers columns to NULL.

```
import sqlite3


path_to_db_file = 'database.db' # Change this to your path
conn = sqlite3.connect(path_to_db_file)
cursor = conn.cursor()

cursor.execute("""
    UPDATE model_instances
    SET distributed_servers = NULL
    WHERE distributed_servers = 'null';
""")

conn.commit()

print(f"Updated {cursor.rowcount} rows.")

cursor.close()
conn.close()
```

---
Updated: Fix verified by the user.

**Comment by winter1215** [comment]
@gitlawr thanks，it works properly

**Comment by Finenyaco** [comment]
If a model instance gets stuck in `Pending` or `Analyzing` status, the `distributed_servers` field in the `model_instances` table will be set to “null,” causing issues when upgrading to v0.7.0.

Another workaround is to revert to previous version, stop the model instances, and then upgrade to v0.7.0.

**Comment by gitlawr** [comment]
Test with RCs.

**Comment by shaguaerdai** [comment]
verified in v0.7.1rc1
